# Generated by Django 4.2.2 on 2023-07-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_studenttable_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='lastName',
            field=models.CharField(max_length=20),
        ),
    ]
