# Generated by Django 4.2.2 on 2023-07-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=100)),
                ('dishReceipe', models.TextField()),
                ('dishImg', models.ImageField(upload_to='dishImg')),
            ],
        ),
    ]
