# Generated by Django 4.2.2 on 2023-08-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegiProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='dishReceipe',
            field=models.TextField(verbose_name='Description of the dish receipe for particular dishs'),
        ),
    ]
