# Generated by Django 4.2.2 on 2023-07-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPage', '0004_alter_studenttable_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='mobNumber',
            field=models.IntegerField(verbose_name='Mobile number of student'),
        ),
    ]
