# Generated by Django 4.2.2 on 2023-07-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPage', '0005_alter_studenttable_mobnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='emailID',
            field=models.EmailField(max_length=254, verbose_name='Student Email ID'),
        ),
    ]
