# Generated by Django 4.2.2 on 2023-07-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPage', '0007_remove_studenttable_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='age1',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
