# Generated by Django 4.2.2 on 2023-08-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPage', '0009_studenttable_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='parentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=50, verbose_name='name of student those parent info need to save')),
                ('fatherName', models.CharField(max_length=60, verbose_name='Student father name')),
                ('motherName', models.CharField(max_length=60, verbose_name='Student mother name')),
                ('mobileNumber', models.IntegerField(verbose_name='student guardian of number')),
                ('occupations', models.CharField(max_length=20)),
            ],
        ),
    ]
