# Generated by Django 4.2.2 on 2023-08-09 09:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPage', '0010_parentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfo',
            name='mobileNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
